name: bwispot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^4.0.0

# Konfigurasi Flutter package
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

# Konfigurasi flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/iconbwis.png"
